### ISSUE TITLE
ImportError: libgnuradio-radar.so

### ISSUE THREAD

**Issue by Dragos17Mih** [kit-cel/gr-radar#15]
Hi ! ctest responds with '100% tests passed' but when I **execute the flowgraph** i get the following error :
Traceback (most recent call last):
  File "/home/mihai/radar/gr-radar/examples/usrp/usrp_echotimer_fmcw.py", line 29, in <module>
    import radar
  File "/usr/local/lib/python2.7/dist-packages/radar/__init__.py", line 45, in <module>
    from radar_swig import *
  File "/usr/local/lib/python2.7/dist-packages/radar/radar_swig.py", line 28, in <module>
    _radar_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/radar/radar_swig.py", line 24, in swig_import_helper
    _mod = imp.load_module('_radar_swig', fp, pathname, description)
**ImportError: libgnuradio-radar.so: cannot open shared object file: No such file or directory**

**Comment by stwunsch** [comment]
Have you tried running 'sudo ldconfig'? Or simply do a reboot!

**Comment by Dragos17Mih** [comment]
thanks ! it worked with 'sudo ldconfig'

**Comment by stwunsch** [comment]
You are welcome!
