### ISSUE TITLE
error on running "USRP_echotimer_FMCW"

### ISSUE THREAD

**Issue by h57jafari** [kit-cel/gr-radar#60]
Hi, I am trying to run "USRP echotimer FMCW" on single USRP X410. Here is what I see in the console and non of GUI open, any help:

usrp_echotimer_cc :info: set_min_output_buffer on block 2 to 98304
Traceback (most recent call last):
  File "/home/sdrusrp/Documents/gnuradio/usrp_echotimer_fmcw.py", line 443, in <module>
    main()
  File "/home/sdrusrp/Documents/gnuradio/usrp_echotimer_fmcw.py", line 421, in main
    tb = top_block_cls()
  File "/home/sdrusrp/Documents/gnuradio/usrp_echotimer_fmcw.py", line 134, in __init__
    self.radar_split_cc_0_0_0 = radar.split_cc(2, (samp_cw/decim_fac,samp_up/decim_fac,samp_down/decim_fac), 'packet_len')
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. gnuradio.radar.radar_python.split_cc(packet_num: int, packet_parts: List[int], len_key: str = 'packet_len')

Invoked with: 2, (2048.0, 2048.0, 2048.0), 'packet_len'

>>> Done (return code 1)

**Comment by h57jafari** [comment]
solved by changing parameters to int.
